{
  "imports": {
    "class": "imports",
    "ATM-SOFT-PVC-MIB": [
      "atmSoftPvcCurrentlyFailingSoftPVpcs",
      "atmSoftPvcCurrentlyFailingSoftPVccs",
      "atmSoftPvcCallFailures",
      "atmSoftPvcTrapsPrefix"
    ],
    "SNMPv2-CONF": [
      "MODULE-COMPLIANCE",
      "NOTIFICATION-GROUP"
    ],
    "SNMPv2-SMI": [
      "Counter32",
      "NOTIFICATION-TYPE",
      "OBJECT-TYPE",
      "IpAddress",
      "TRAP-TYPE",
      "Bits",
      "MODULE-IDENTITY",
      "iso",
      "Integer32",
      "OBJECT-IDENTITY",
      "Unsigned32",
      "MibIdentifier",
      "Gauge32",
      "Counter64",
      "TimeTicks"
    ],
    "SNMPv2-TC": [
      "TEXTUAL-CONVENTION",
      "DisplayString"
    ]
  },
  "atmSoftPvcCallFailuresTrap": {
    "name": "atmSoftPvcCallFailuresTrap",
    "oid": "1.3.6.1.4.1.353.5.5.1.2.1.00.1",
    "class": "notificationtype",
    "objects": [
      {
        "module": "ATM-SOFT-PVC-MIB",
        "object": "atmSoftPvcCallFailures"
      },
      {
        "module": "ATM-SOFT-PVC-MIB",
        "object": "atmSoftPvcCurrentlyFailingSoftPVccs"
      },
      {
        "module": "ATM-SOFT-PVC-MIB",
        "object": "atmSoftPvcCurrentlyFailingSoftPVpcs"
      }
    ],
    "description": "A notification indicating that one or more series of call attempts in trying to establish a Soft PVPC or Soft PVCC have failed since the last atmSoftPvcCallFailureTrap was sent. If this trap has not been sent for the last atmSoftPvcNotificationInterval, then it will be sent on the next increment of atmSoftPvcCallFailures."
  },
  "meta": {
    "comments": [
      "ASN.1 source file://MIBS/asn1/ATM-SOFT-PVC-TRAP-MIB.mib",
      "Produced by pysmi-0.3.4 at Tue Apr 20 17:57:31 2021",
      "On host samy-ThinkPad-T495s platform Linux version 5.8.0-50-generic by user root",
      "Using Python version 3.8.5 (default, Jan 27 2021, 15:41:15) "
    ],
    "module": "ATM-SOFT-PVC-TRAP-MIB"
  }
}